# Generated by Django 3.1 on 2020-09-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
