# Generated by Django 3.1 on 2020-10-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0003_slot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slot',
            new_name='Appointment',
        ),
    ]
