# Generated by Django 3.1 on 2020-10-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0005_auto_20201015_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_item', models.CharField(max_length=200, null=True)),
                ('main_weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_item', models.CharField(max_length=200, null=True)),
                ('sub_weight', models.IntegerField(null=True)),
                ('main_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premiers.mainpurpose')),
            ],
        ),
    ]
