# Generated by Django 3.1 on 2020-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0008_auto_20201015_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpurpose',
            name='main_item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subpurpose',
            name='sub_item',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
