# Generated by Django 3.1 on 2020-10-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0009_auto_20201015_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpurpose',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='MainPurpose_pics'),
        ),
    ]
