# Generated by Django 3.1 on 2020-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0010_mainpurpose_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpurpose',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='MainPurpose_pics'),
        ),
    ]
