# Generated by Django 3.1 on 2020-10-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0012_auto_20201029_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='com_type',
            new_name='company_Type',
        ),
    ]
