# Generated by Django 3.1 on 2020-10-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0013_auto_20201029_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_item', models.CharField(max_length=200, null=True)),
                ('company_weight', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_item', models.CharField(max_length=200, null=True)),
                ('job_weight', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_item', models.CharField(max_length=200, null=True)),
                ('title_weight', models.FloatField(null=True)),
            ],
        ),
    ]
