# Generated by Django 3.1 on 2020-11-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0015_purposeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='company_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premiers.company'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premiers.title'),
        ),
    ]
