# Generated by Django 3.1 on 2020-11-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0016_auto_20201118_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='position',
            new_name='job',
        ),
    ]
