# Generated by Django 3.1 on 2020-11-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0017_auto_20201118_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='job',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='vip',
            name='company_Type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.title'),
        ),
    ]
