# Generated by Django 3.1 on 2020-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0018_auto_20201118_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
