# Generated by Django 3.1 on 2020-11-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0019_auto_20201118_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.title'),
        ),
    ]
