# Generated by Django 3.1 on 2020-11-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0021_auto_20201118_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.job'),
        ),
    ]
