# Generated by Django 3.1 on 2020-11-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0022_auto_20201118_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='job_item',
            new_name='position_item',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='job_weight',
            new_name='position_weight',
        ),
    ]
