# Generated by Django 3.1 on 2020-11-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0023_auto_20201118_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='CompanyType',
        ),
    ]
