# Generated by Django 3.1 on 2020-11-18 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premiers', '0024_auto_20201118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='company_Type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.companytype'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='position',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.position'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='title',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.title'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
