# Generated by Django 3.1 on 2020-12-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0026_auto_20201118_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventDummy',
        ),
    ]
