# Generated by Django 3.1 on 2020-12-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0027_auto_20201222_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurposeItem',
        ),
    ]
