# Generated by Django 3.1 on 2020-12-28 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premiers', '0028_delete_purposeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premiers.mainpurpose')),
                ('sub_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premiers.subpurpose')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.vip')),
            ],
        ),
    ]
