# Generated by Django 3.1 on 2020-12-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0029_purposedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purposedetail',
            name='main_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.mainpurpose'),
        ),
        migrations.AlterField(
            model_name='purposedetail',
            name='sub_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.subpurpose'),
        ),
    ]
