# Generated by Django 3.1 on 2021-01-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0030_auto_20201228_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpurpose',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
