# Generated by Django 3.1 on 2021-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0031_mainpurpose_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpurpose',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
