# Generated by Django 3.1 on 2021-01-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0032_auto_20210104_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpurpose',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mainpurpose',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
