# Generated by Django 3.1 on 2021-01-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0034_purposedetail_fuzzy_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='purposedetail',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
