# Generated by Django 3.1 on 2021-01-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0035_purposedetail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purposedetail',
            old_name='name',
            new_name='category',
        ),
    ]
