# Generated by Django 3.1 on 2021-01-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0036_auto_20210107_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
