# Generated by Django 3.1 on 2021-01-07 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0037_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='purposedetail',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.representative'),
        ),
    ]
