# Generated by Django 3.1 on 2021-01-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0033_auto_20210104_1655'),
        ('events', '0006_auto_20210104_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='iSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the event', verbose_name='Date of the event')),
                ('purpose_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='premiers.purposedetail')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.slot')),
            ],
            options={
                'verbose_name': 'Instant Slot',
                'verbose_name_plural': ' Instant Slot',
            },
        ),
    ]
