# Generated by Django 3.1 on 2021-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
