# Generated by Django 3.1 on 2021-01-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_representative_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
